### ISSUE TITLE
A valid semver tag (e.g. v1.0.0) was not found even though it exists

### ISSUE THREAD

**Issue by cdavernas** [cbcrouse/Versioning.NET#25]
**Describe the bug**
When using the tool in a Github pipeline, it will systematically return the following message:

```
Tool 'versioning.net' (version '0.5.0') was successfully installed.
info: Application.GitVersioning.Handlers.GetCommitVersionInfosHandler[0]
      A valid semver tag (e.g. v1.0.0) was not found. Please add a valid semver tag to your repository and try again.
info: Application.GitVersioning.Handlers.IncrementVersionWithGitIntegrationHandler[0]
      Increment 'Unknown' was determined from the commits.
```

**To Reproduce**
1. Create a Github pipeline such as the following:

```
name: CI

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure remote repository
        run: |
          git remote set-url origin "https://[user]:[password]@github.com/[repo]/test.git"
          dotnet tool install --global Versioning.NET
          dotnet-version increment-version-with-git -g "." --branch-name main --author-email pipeline@github.com
```

2. Push a commit with a message such as:

```
fix(Versioning): Fixed issue where git tag could not be found
```

3. When running, the pipeline will show the message described above, and the new version is not computed

**Expected behavior**
A new version is successfully computed

**Additional context**
I did tag the repository with a SemVer (v0.1.0) before running the tool, but it did not change a thing 😢 
Furthermore, shouldn't semantic versions NOT be prefixed with the 'v' character, as explained in this [issue](https://github.com/semver/semver/issues/204#issuecomment-99771279)?

**Comment by cdavernas** [comment]
@cbcrouse Did you have time to check it out? 
I'm trying to get it to work for [CNCF Synapse](https://github.com/serverlessworkflow/synapse). 
If you have time, it would be absolutely amazing if you could contribute with a PR to add a pipeline for your awesome tool.

**Comment by cbcrouse** [comment]
Hey @cdavernas I apologize, I don't recall seeing a notification of this issue, so thanks for following up on it. I'll have some time tomorrow to review this in more detail.

> Furthermore, shouldn't semantic versions NOT be prefixed with the 'v' character, as explained in this [issue](https://github.com/semver/semver/issues/204#issuecomment-99771279?)

The versions in the project files themselves do not contain the 'v' character however, it helps to find the version tag when traversing through potentially many numeric-only tags such as dates. The SemVer C# library supports the 'v' when accepting the string formatted value and works quite well.

**Comment by cbcrouse** [comment]
Hi @cdavernas - I was able to resolve this issue by setting the `fetch-depth` value of the [checkout](https://github.com/actions/checkout) task to `0`. I've added this as a troubleshooting step to a new section in the [wiki](https://github.com/cbcrouse/Versioning.NET/wiki/Configuring-CI-CD#troubleshooting).

**Example**
```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
```

While I was troubleshooting, I also stumbled upon an unhandled exception for missing csproj files so I've published a fix for that. However, this issue did not require any code changes. Can you let me know if following the same steps also resolves your issue?
